apiVersion: v1
kind: Service
metadata:
  name: jupiter-app
  namespace: jupiter
  labels:
    app: jupiter
spec:
  type: LoadBalancer
  selector:
    app: jupiter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
