sonar.projectKey=aws-enterprise-devsecops-platform
sonar.projectName=AWS Enterprise DevSecOps Platform
sonar.projectVersion=1.0

sonar.sources=app/src,terraform
sonar.exclusions=**/.terraform/**,**/*.tfstate,**/*.tfstate.backup,**/node_modules/**,**/*.md,**/.dockerignore,k8s/**

sonar.sourceEncoding=UTF-8
